graph TD;
    A[开始] --> B[先升级nexus 3.70版本]
    B --> C[登录3.70控制台备份数据]
    C --> D[使用nexus-db-migrator-3.70.3-01.jar迁移数据到h2数据库]
    D --> E[升级nexus版本到nexus-3.79.1-04]
    E --> F[配置文件配置2个配置；复制h2数据库文件]
    F --> G[启动新服务]
    G --> H[结束]